url: "https://bolternie.github.io"
baseurl: "/YueYu.github.io"
# Basic Information
title: Yue Yu
# subtitle:
position: Incoming Ph.D. Student
subposition: Stata Family Presidential Fellow
subposition_link: https://oge.mit.edu/fellowships/presidential-graduate-fellowship-program/
affiliation: MIT EECS
# subaffiliation:
affiliation_link: https://www.eecs.mit.edu/
# subaffiliation_link:
email: yueyu518@mit.edu
address: 77 Massachusetts Avenue, Cambridge, MA 02139, USA
address_link: https://www.google.com/maps/search/?api=1&query=77+Massachusetts+Avenue+Cambridge+MA+02139

# Search Engine Optimization (SEO)
# The following information is used to improve the website traffic from search engines, e.g., Google.
keywords: Yue Yu, MIT, EECS, Electrical Engineering
description: Personal homepage of Yue Yu, incoming Ph.D. student in EECS at MIT.
canonical: https://bolternie.github.io/YueYu.github.io/

# Links
# If you don't need one of them, you may delete the corresponding line.
google_scholar: https://scholar.google.com/citations?user=ksw4gJsAAAAJ&hl=en
orcid: https://orcid.org/0000-0002-9667-1487
# cv_link:
github_link: https://github.com/Bolternie
linkedin: https://www.linkedin.com/in/yue-yu-954239352/
# twitter:

# Images (e.g., your profile picture and your website's favicon)
# "favicon" and "favicon_dark" are used for the light and dark modes, respectively.
avatar: ./assets/img/yueyu.jpg
# logo: ./assets/img/logo.png
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon.png

# Footnote
# You may use the option to disable the footnote, "Powered by Jekyll and Minimal Light theme."
enable_footnote: false

# Google Analytics ID
# Please remove this if you don't use Google Analytics
# google_analytics:

# Use this project as a remote theme for GitHub Pages
# See the guide here: https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/adding-a-theme-to-your-github-pages-site-using-jekyll
remote_theme: yaoyao-liu/minimal-light

# The following files will be removed from the generated website.
exclude:
  - vendor
  - Gemfile
  - Gemfile.lock
  - README.md
  - README_zh_Hans.md
  - README_zh_Hant.md
  - README_de.md
  - LICENSE
  - minimal-light.gemspec
